### PR TITLE
Implementing Internationalization

### PR DESCRIPTION
**Pull request by iamalisajid**
Added basic language button and installed `react-intl` for implementing Internationalization in our app.

Demo:
image

### CODE REVIEW

**Comment by InamTaj** [comment]
Not just integrate it, make it functional. Your whole app's text should be translated into the user selected language when he makes a selection from language dropdown.

**Comment by iamalisajid** [comment]
Yes, I am currently working on it, just pushed the changes as an initial commit of this branch.

**Comment by InamTaj** [comment]
PRs and reviews are meant for completed work not for partial work

**Comment by iamalisajid** [comment]
Added Russian language with the app, a slight issue is present with the language drop-down. Will fix it later.
Demo: https://www.useloom.com/share/ae375a4e92104438b0f97074737223b2

**Comment by iamalisajid** [comment]
Fixed the drop-down glitch. 
Demo: https://www.useloom.com/share/a1680854a77044fd88c20384755af527

**Comment by InamTaj** [comment]
Learn SSR (Server-side Rendering) in React from some good & latest resources and start implementing it in the project

**Pull request merged**
